sudo: required
language: sh

os: osx

before_script:
  - brew install shellcheck
  # we need rvm keys
  - curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  - curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

script:
  - shellcheck ./mac && ./mac

notifications:
  email: false

branches:
  only:
    - master
