sudo: required
language: sh

before_script:
  - sudo apt-get -y update
  - sudo apt-get -y install shellcheck

os: osx

script:
  - ./mac

notifications:
  email: false

# branches:
#   only:
#     - master
