sudo: required
language: sh

before_script:
  - sudo apt-get -y update
  - sudo apt-get -y install shellcheck

os: osx

before_script:
  # we need rvm keys
  - curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  - curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
script:
  - ./mac

notifications:
  email: false

branches:
  only:
    - master
